opensslwrapper.cpp: fix compile errors on Windows
Needed to include windows.h:

    ..\src\common\opensslwrapper.cpp(52): error C2065: 'PVOID': undeclared identifier
    ..\src\common\opensslwrapper.cpp(52): error C2065: 'ULONG': undeclared identifier
    ..\src\common\opensslwrapper.cpp(52): error C2165: 'left-side modifier': cannot modify pointers to data
    ..\src\common\opensslwrapper.cpp(52): error C2513: 'BYTE *': no variable declared before '='
    ..\src\common\opensslwrapper.cpp(58): error C3861: 'LoadLibraryA': identifier not found
    ..\src\common\opensslwrapper.cpp(58): error C3861: 'GetProcAddress': identifier not found
    ..\src\common\opensslwrapper.cpp(60): error C2064: term does not evaluate to a function taking 2 arguments

Signed-off-by: Steven Noonan <steven@valvesoftware.com>